"""Grokking Functional Programming - Python implementation."""

from grokking_fp.ch01_intro import (
    absolute,
    add,
    clamp,
    double,
    get_first_character,
    greet,
    increment,
    is_empty,
    is_even,
    is_positive,
    max_value,
    min_value,
    reverse_string,
    to_uppercase,
    word_score,
)
from grokking_fp.ch02_pure_functions import (
    all_positive,
    any_negative,
    average,
    bonus_score,
    calculate_discount,
    calculate_final_price,
    calculate_tip,
    count_vowels,
    double_all,
    filter_positive,
    find_longest,
    get_discount_percentage,
    get_tip_percentage,
    sum_list,
    word_score_no_a,
)

__all__ = [
    # ch01
    "increment",
    "word_score",
    "get_first_character",
    "add",
    "double",
    "greet",
    "to_uppercase",
    "reverse_string",
    "absolute",
    "max_value",
    "min_value",
    "clamp",
    "is_even",
    "is_positive",
    "is_empty",
    # ch02
    "bonus_score",
    "get_discount_percentage",
    "calculate_discount",
    "calculate_final_price",
    "get_tip_percentage",
    "calculate_tip",
    "count_vowels",
    "double_all",
    "filter_positive",
    "find_longest",
    "all_positive",
    "any_negative",
    "sum_list",
    "average",
    "word_score_no_a",
]
