name:                grokkingfp
version:             0.1.0.0
synopsis:            Grokking Functional Programming examples in Haskell
description:         Implementation of FP concepts from "Grokking Functional Programming"
license:             MIT
author:              Project Team
maintainer:
category:            Education

extra-source-files:
- README.md

dependencies:
- base >= 4.14 && < 5
- text
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Ch01.IntroHaskell
    - Ch02.PureFunctions
    - Ch03.ImmutableValues
    - Ch04.FunctionsAsValues
    - Ch05.SequentialPrograms
    - Ch06.MaybeHandling
    - Ch07.EitherHandling
    - Ch08.IOMonad
    - Ch09.StreamProcessing
  dependencies:
    - random

tests:
  grokkingfp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grokkingfp
    - hspec
    - QuickCheck
